version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 4
    ignore-failure: false
    
phases:
  install:
    commands:
      - echo 'Installing Node.js dependencies'
      # - apt-get update
      # - apt-get install -y nodejs
      # - npm install
      - npm install --save-dev jest-junit
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Running JavaScript Tests'
      - echo $CODEBUILD_TOTAL_SHARDS
      - echo $CODEBUILD_CURRENT_SHARD
      - echo $(codebuild-glob-search '**/src/test/*.js')
      - |
         codebuild-tests-run \
          --test-command 'npx jest --runInBand --coverage' \
          --files-search "codebuild-glob-search '**/src/test/**/*.test.js'" \
          --sharding-strategy 'equal-distribution'
    post_build:
      commands:
        - echo 'Test execution completed'

reports:
  test-reports:
    files:
      - '**/*'               
    base-directory: 'test-reports'
    file-format: JunitXml
  coverage-reports:
    files:
      - '**/*'               
    base-directory: 'coverage'
    file-format: CLOVERXML 

artifacts:
  files:
    - 'test-reports/**/*'
    - 'coverage/**/*'
  name: build-reports-$(date +%Y-%m-%d)
