version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 4
    ignore-failure: false
    
phases:
  install:
    commands:
      - echo 'Installing Node.js dependencies'
      - npm install jest-junit --save-dev
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Running JavaScript Tests'
      - echo $CODEBUILD_TOTAL_SHARDS
      - echo $CODEBUILD_CURRENT_SHARD
      - echo "Printing all env vars"
      - printenv
      - echo 'Sleeping for 5 mins'
      - sleep 600
      - echo 'Woke up after 5 mins'
      - echo $(codebuild-glob-search '**/src/test/*.js')
      - |
         codebuild-tests-run \
          --test-command 'npx jest --runInBand --coverage' \
          --files-search "codebuild-glob-search '**/src/test/**/*.test.js'" \
          --sharding-strategy 'equal-distribution' 
    post_build:
      commands:
        - echo 'Test execution completed'
